# categories.py

CATEGORIES_LIST = [
    "Accommodation and Food Services",
    "Advertising and Marketing",
    "Agriculture, Forestry, Fishing and Hunting",
    "Arts, Entertainment, and Recreation",
    "Automotive",
    "Construction",
    "Consulting and Business Services",
    "Consumer Services",
    "E-commerce",
    "Education",
    "Energy and Utilities",
    "Finance",
    "Insurance",
    "Healthcare",
    "Hospitality",
    "Information Technology",
    "Manufacturing",
    "Mining and Quarrying",
    "Non-Profit",
    "Professional, Scientific, and Technical Services",
    "Public Administration",
    "Real Estate",
    "Retail",
    "Telecommunications",
    "Transportation and Warehousing",
    "Travel",
    "Wholesale Trade",
    "Other"
]
